
import { pgTable, text, integer, real, bigint, timestamp } from 'drizzle-orm/pg-core';

// ─── submissions table (regular Postgres table) ───────────────────────────────

export const submissions = pgTable('submissions', {
  id: text('id').primaryKey(),                          // UUID v4, generated by gateway
  contestantId: text('contestant_id').notNull(),        // from JWT sub claim
  language: text('language', { enum: ['cpp', 'rust', 'go'] }).notNull(),
  artifactPath: text('artifact_path').notNull(),        // MinIO key: {id}/{filename}
  status: text('status', {
    enum: ['queued', 'building', 'running', 'stopped', 'error'],
  })
    .notNull()
    .default('queued'),
  containerHost: text('container_host'),                // set by sandbox after container starts
  containerPort: integer('container_port'),             // set by sandbox after container starts
  submittedAt: timestamp('submitted_at', { withTimezone: true }).notNull().defaultNow(),
  startedAt: timestamp('started_at', { withTimezone: true }),
  stoppedAt: timestamp('stopped_at', { withTimezone: true }),
});

// ─── users table ──────────────────────────────────────────────────────────────

export const users = pgTable('users', {
  id:           text('id').primaryKey(),                 // UUID v4, generated by gateway
  username:     text('username').notNull().unique(),     // team name or individual handle
  passwordHash: text('password_hash').notNull(),
  role:         text('role', { enum: ['admin', 'contestant'] })
                  .notNull()
                  .default('contestant'),
  createdAt:    timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export type UserRow    = typeof users.$inferSelect;
export type NewUser    = typeof users.$inferInsert;


// ─── metrics table (will be converted to hypertable by migration 002) ────────

export const metrics = pgTable('metrics', {
  time: timestamp('time', { withTimezone: true }).notNull(),
  submissionId: text('submission_id').notNull(),        // soft FK to submissions.id
  latencyP50: real('latency_p50').notNull().default(0),
  latencyP90: real('latency_p90').notNull().default(0),
  latencyP99: real('latency_p99').notNull().default(0),
  tps: real('tps').notNull().default(0),
  correctnessRate: real('correctness_rate').notNull().default(0),
  compositeScore: real('composite_score').notNull().default(0),
  totalOrders: bigint('total_orders', { mode: 'number' }).notNull().default(0),
  correctFills: bigint('correct_fills', { mode: 'number' }).notNull().default(0),
  totalFills: bigint('total_fills', { mode: 'number' }).notNull().default(0),
});

// ─── Inferred types (use these in services instead of the manual interfaces) ──

export type SubmissionRow = typeof submissions.$inferSelect;
export type NewSubmission = typeof submissions.$inferInsert;

export type MetricRow = typeof metrics.$inferSelect;
export type NewMetric = typeof metrics.$inferInsert;
